### PR TITLE
Add DAG-based consensus papers and category

### PR DESCRIPTION
**Pull request by OrfeasLitos**
## Checklist for submitting a pull request to `blockchain-papers`:

- [x] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/decrypto-org/blockchain-papers/blob/master/CONTRIBUTING.md) of this repo.
- [x] I have **searched** the [PRs](https://github.com/decrypto-org/blockchain-papers/pulls) of this repo and believe that this is not a duplicate.

 

- **Title**: Snowflake to Avalanche: A Novel Metastable Consensus Protocol Family for Cryptocurrencies
- **Link**: https://ipfs.io/ipfs/QmUy4jh5mGNZvLkjies1RWM4YuvJh5o2FYopNPVYwrRVGV
- **Category**: DAG-based consensus
---
- **Title**: Scaling Nakamoto Consensus to Thousands of Transactions per Second
- **Link**: https://arxiv.org/pdf/1805.03870.pdf
- **Category**: DAG-based consensus
---
- **Title**: Blockchain-Free Cryptocurrencies: A Framework for Truly Decentralised Fast Transactions 
- **Link**: https://eprint.iacr.org/2016/871.pdf
- **Category**: DAG-based consensus
---
- **Title**: The Tangle
- **Link**: https://assets.ctfassets.net/r1dr6vzfxhev/2t4uxvsIqk0EUau6g2sw0g/45eae33637ca92f85dd9f4a3a218e1ec/iota1_4_3.pdf
- **Category**: DAG-based consensus
---
- **Title**: DAGcoin Whitepaper
- **Link**: https://dagcoin.org/wp-content/uploads/2018/10/DAGCOIN-WHITEPAPER-v03.pdf
- **Category**: DAG-based consensus
---
- **Title**: Byteball: A Decentralized System for Storage and Transfer of Value
- **Link**: https://byteball.org/Byteball.pdf
- **Category**: DAG-based consensus

### CODE REVIEW

**Comment by OrfeasLitos** [comment]
Papers added in order of (subjective) quality

**Comment by OrfeasLitos** [comment]
Fixed GraphChain (now is "Blockchain-Free Cryptocurrencies [...]"). DAGcoin works for me.

**Comment by dimkarakostas** [comment]
DAGcoin still not working for me (404 not found). Maybe your browser has cached it? I have found [this](https://dagcoin.org/whitepaper.pdf) though, which I assume is the same one.

**Comment by OrfeasLitos** [comment]
I've tried the DAGcoin link on multiple machines, it always works for me. The link you provide is not the latest version. Both links lead to a "Draft version 0.3", but the link I provide is dated 14/5/2018. Can someone else see if https://dagcoin.org/wp-content/uploads/2018/10/DAGCOIN-WHITEPAPER-v03.pdf works?

**Comment by dionyziz** [comment]
I veto the inclusion of "The Tangle". It is an unscientific paper, unreviewed paper with unsubstantiated results.

**Comment by dionyziz** [comment]
Have any of these papers been published in peer-reviewed academic conferences?

**Comment by cnasikas** [comment]
> I've tried the DAGcoin link on multiple machines, it always works for me. The link you provide is not the latest version. Both links lead to a "Draft version 0.3", but the link I provide is dated 14/5/2018. Can someone else see if https://dagcoin.org/wp-content/uploads/2018/10/DAGCOIN-WHITEPAPER-v03.pdf works?

The URL is working now. It's truth that it was dead when @dimkarakostas posted.

**Comment by dimkarakostas** [comment]
DAGcoin is still not working on my machine (tried Firefox Normal/Incognito & Tor). Not sure why but I guess I will not be the only one with this problem, so maybe keep this paper in the backlog if they fix it or otherwise add the older version I posted above which is working.

**Comment by dimkarakostas** [comment]
> Have any of these papers been published in peer-reviewed academic conferences?

@dionyziz the repo contains various non peer-reviewed papers, so is this a strong requirement? Cause in this case we would have to remove everything that is not peer-reviewed.

**Comment by OrfeasLitos** [comment]
I put the [DAGcoin link](https://dagcoin.org/whitepaper.pdf) @dimkarakostas proposed and removed [the Tangle](https://assets.ctfassets.net/r1dr6vzfxhev/2t4uxvsIqk0EUau6g2sw0g/45eae33637ca92f85dd9f4a3a218e1ec/iota1_4_3.pdf).

**Comment by OrfeasLitos** [comment]
@dimkarakostas @dionyziz I've made the changes you requested, let's have some progress with this PR.

**Pull request merged**
