### PR TITLE
Add new Application section

### PR DESCRIPTION
**Pull request by preetsinojiya**
This is one of the best sources to find good research papers about blockchain, but it lacks the papers that aim at the use of blockchain and trying to make a good product out it. I think it will add more value if we can have section which contains the whitepapers of the blockchain products/applications.

### CODE REVIEW

**Comment by cnasikas** [comment]
Thanks a lot for your kind words! I think an application section would be a good addition.

Please squash your commits into one.

**Comment by preetsinojiya** [comment]
Please tell if anything else needs to be done!

**Comment by cnasikas** [comment]
Nice. The url of storj white paper is missing. Please add `https://storj.io/storj.pdf`

**Comment by preetsinojiya** [comment]
Oh sorry, my bad! Done.

**Pull request merged**
