### PR TITLE
Add two new papers about consensus

### PR DESCRIPTION
**Pull request by hzxGoForward**
## Checklist for submitting a pull request to `blockchain-papers`:

- [x] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/decrypto-org/blockchain-papers/blob/master/CONTRIBUTING.md) of this repo.
- [x] I have **searched** the [PRs](https://github.com/decrypto-org/blockchain-papers/pulls) of this repo and believe that this is not a duplicate.

 

- **Title**: Bitcoin-NG: A Scalable Blockchain Protocol
- **Link**: https://www.usenix.org/system/files/conference/nsdi16/nsdi16-paper-eyal.pdf 
- **Category**: Consensus 

- **Title**: Resource-Efficient Mining for Blockchains
- **Link**: https://www.usenix.org/system/files/conference/usenixsecurity17/sec17-zhang.pdf 
- **Category**: Consensus

### CODE REVIEW

**Comment by dionyziz** [comment]
You seem to be replaying commits from 4 months ago here, are you sure that this is what you intended?

**Comment by hzxGoForward** [comment]
> You seem to be replaying commits from 4 months ago here, are you sure that this is what you intended?

I had modified my commit format，It's a mistake.

**Comment by dionyziz** [comment]
OK. Please fix the commit history, push force, and let us know so that we can review your pull request. Thank you :)

**Comment by dionyziz** [comment]
I'm closing this. If you plan to take a look at it, please request a reopen. Thanks!

**Pull request closed without merging**
