### PR TITLE
Add Non-Interactive Proofs of Proof-of-Work

### PR DESCRIPTION
**Pull request by k4m4**
## Checklist for submitting a pull request to `blockchain-papers`:

- [X] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/decrypto-org/blockchain-papers/blob/master/CONTRIBUTING.md) of this repo.
- [x] I have **searched** the [PRs](https://github.com/decrypto-org/blockchain-papers/pulls) of this repo and believe that this is not a duplicate.

 

- **Title**: Non-Interactive Proofs of Proof-of-Work
- **Link**: https://eprint.iacr.org/2017/963.pdf
- **Category**: Proof of work

### CODE REVIEW

**Comment by k4m4** [comment]
@dionyziz Maybe this is a good addition to the list? ;)

**Comment by dionyziz** [comment]
This has not been accepted to USENIX, so I would include it as a reference to eprint only. If it is accepted and the proceedings version becomes available, we can change it. Can you make the change so that the reference is only to eprint? Thanks!

**Comment by k4m4** [comment]
Sounds good. Should I change `USENIX` to `IACR` or `ePrint`?

**Comment by dionyziz** [comment]
As none of `IACR` or `ePrint` are conferences or journals, just remove it altogether, similar to the other papers that list just the authors.

**Comment by dionyziz** [comment]
Looks good, would you kindly squash your two commits into the first so that we can merge?

**Comment by k4m4** [comment]
Done.

**Comment by dionyziz** [comment]
By the way, let's move this paper to the sidechain section together with KLS16 which is already there? Proofs of proofs of work are less about proof of work itself and more about proof of proof of work :p

**Comment by cnasikas** [comment]
Fixed #38

**Pull request merged**
