### PR TITLE
Added two articles

### PR DESCRIPTION
**Pull request by juliarainbowx**
## Checklist for submitting a pull request to `blockchain-papers`:

- [x] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/decrypto-org/blockchain-papers/blob/master/CONTRIBUTING.md) of this repo.
- [x] I have **searched** the [PRs](https://github.com/decrypto-org/blockchain-papers/pulls) of this repo and believe that this is not a duplicate.

 

- **Title**: 
- **Link**: 
- **Category**:

### CODE REVIEW

**Comment by cnasikas** [comment]
Hi, thanks for your contribution. "Proof-of-property" is published on IEEE. Please include the publication.

**Comment by OrfeasLitos** [comment]
Thanks a lot! Can you squash the commits as well?

**Comment by dionyziz** [comment]
Could you include the conference so that we can merge this? @juliarainbowx

**Comment by dimkarakostas** [comment]
@juliarainbowx what is the status of this PR?

**Comment by dionyziz** [comment]
Closing until further notice.

**Pull request closed without merging**
