### PR TITLE
Added "Information Propagation in Bitcoin Network" under Networks

### PR DESCRIPTION
**Pull request by AkashSarda**
Added a good paper on low level aspects of implementation of blockchains.
It is a good paper talking about propagation delay and is instrumental to anyone researching on Blockchain Scaling.

### CODE REVIEW

**Comment by cnasikas** [comment]
Thanks! Please change commit messages to use the [imperative](https://chris.beams.io/posts/git-commit/) and fix broken URL.

**Comment by AkashSarda** [comment]
Done.

**Comment by AkashSarda** [comment]
Done.

**Comment by cnasikas** [comment]
Great! Sorry to bother again but each pull request should be one clean commit with all suggested changes. Please squash them into one with all changes included.

Also please change `Decker, C., Wattenhofer, R. IEEE P2P. (2013)` to `Decker C, Wattenhofer R. IEEE P2P '13.`

**Comment by AkashSarda** [comment]
I took the citation from a published paper so it should not be a problem.

**Comment by AkashSarda** [comment]
Okay fine.

**Comment by AkashSarda** [comment]
Look it up. Done.

**Comment by cnasikas** [comment]
Perfect! Please change the citation to `please change Decker, C., Wattenhofer, R. IEEE P2P. (2013) to Decker C, Wattenhofer R. IEEE P2P '13.` and is ready to be accepted.

> I took the citation from a published paper so it should not be a problem.

I understand but if you see we follow a standard formatting and yours deviates from it.

**Comment by AkashSarda** [comment]
I have committed again. Look it up.

**Comment by cnasikas** [comment]
Thanks a lot but I don't see any citation changes. The commit is perfect, one and clean. Only the citation needs to be changed.

**Pull request closed without merging**
