### PR TITLE
Add peer-review badge

### LINKED ISSUE #53: Peer-reviewed badge
We could add a badge next to every paper that is peer-reviewed (including also the conference perhaps?), so that the users can easily see which has been presented at a conference and which is self-published.

### PR DESCRIPTION
**Pull request by dimkarakostas**
Fix #53

### CODE REVIEW

**Comment by cnasikas** [comment]
To be honest I do not like that much the emoji. Let's vote. It's serious :)

My preferences:

:boom:
:star:
:+1:
:ok_hand:
:mortar_board:
:pencil:
:white_check_mark:

**Comment by cnasikas** [comment]
:boom:

**Comment by cnasikas** [comment]
:star:

**Comment by cnasikas** [comment]
:+1:

**Comment by cnasikas** [comment]
:ok_hand:

**Comment by cnasikas** [comment]
:mortar_board:

**Comment by cnasikas** [comment]
:pencil:

**Comment by cnasikas** [comment]
:white_check_mark:

**Comment by cnasikas** [comment]
> 🎓

We have a winner right ?

**Comment by cnasikas** [comment]
@dimkarakostas Do you mind change (rebase) to the new elected badge ?

**Comment by dimkarakostas** [comment]
Rebased and fixed it.

**Pull request merged**
