### PR TITLE
Systematic Review Paper added

### PR DESCRIPTION
**Pull request by itzpc**
## Checklist for submitting a pull request to `blockchain-papers`:

- [x] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/decrypto-org/blockchain-papers/blob/master/CONTRIBUTING.md) of this repo.
- [x] I have **searched** the [PRs](https://github.com/decrypto-org/blockchain-papers/pulls) of this repo and believe that this is not a duplicate.

### CODE REVIEW

**Comment by itzpc** [comment]
Direct link to pdf is added but token will get expire and will be redirected to science direct page automatically. People have to click on the download option in the science direct site to access the paper. They have developed their website accordingly. 

Sorry It is not a mistake from my end and I cannot do anything on this . 

The paper is open source and it is a direct link to Science Direct journal. It is a must read paper in blockchain. I highly recommend you add this to your collections 

Thanks.

**Comment by dionyziz** [comment]
Here is a direct link outside of Elsevier's website:

https://www.researchgate.net/profile/Thomas_Dasaklis/publication/329136952_A_systematic_literature_review_of_blockchain-based_applications_Current_status_classification_and_open_issues/links/5c4cab1ba6fdccd6b5cb7ea1/A-systematic-literature-review-of-blockchain-based-applications-Current-status-classification-and-open-issues.pdf

Based on their unethical business practices and general immoral existence, we should avoid linking to Elsevier's website until we can ban all their publications altogether.

**Comment by OrfeasLitos** [comment]
Thanks for your quick reply.

The author list still doesn't follow the format: Authors' first names should be after the last name without a `,` in between the two and abbreviated to a single letter. No `and` for the last author.

A space is missing after the author list and before the year. Also better write `Elsevier '18` instead of `'18 (Published in Elsevier)`

**Comment by dionyziz** [comment]
The conference name is "Telematics and Informatics". Elsevier is the publisher, which should not appear.

(Besides, we don't want to promote Elsevier.)

**Comment by OrfeasLitos** [comment]
Last lint and I promise I'll merge after that: Add `.` at the end, after the year.

**Comment by OrfeasLitos** [comment]
Thanks for asking. I believe that having a uniform style in this page is good. In principle I don't mind such tiny mistakes. But. If we allow minor discrepancies, new contributors may copy off of these and add theirs on top. It's a matter of weeks until we end up with very inconsistent styles between references.

Sorry for being such a pedant and thanks for the contribution!

**Pull request merged**
