### PR TITLE
Added a paper and a new section named "system"

### PR DESCRIPTION
**Pull request by grammaright**
Hello.
I added a paper and I think this is not good to place any other section so I created a new section named "system".
If you think it is not properly placed, please comment.

## Checklist for submitting a pull request to `blockchain-papers`:

- [x] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/decrypto-org/blockchain-papers/blob/master/CONTRIBUTING.md) of this repo.
- [x] I have **searched** the [PRs](https://github.com/decrypto-org/blockchain-papers/pulls) of this repo and believe that this is not a duplicate.

### CODE REVIEW

**Comment by dionyziz** [comment]
IF we're going to be creating a new section, we should see if other papers in the list are more suitable to be moved to that section. Otherwise it does not mandate a whole section just for one paper. If not, we should see what existing section it is more suited for.

**Comment by OrfeasLitos** [comment]
@grammaright Doesn't it fit in the "Applications" section?

**Comment by grammaright** [comment]
@dionyziz @OrfeasLitos 
I do not agree wholly with @OrfeasLitos 's opinion (because the added paper is not using blockchain but propose a new data structure for blockchain), but it is not bad.
So I added a commit accordingly. (Removed "system" section and moved forkbase to "Applications")

**Comment by dimkarakostas** [comment]
What is the status of this PR? @grammaright @dionyziz @OrfeasLitos 
Btw looking at the paper, it seems that it might fit under `Sidechains, Higher layer and Scalability` also.
Also @grammaright please squash your commits into a single commit before merging to keep a clean repo history.

**Comment by OrfeasLitos** [comment]
@dimkarakostas on second thought, I agree it fits better in the "Scalability" section. @grammaright if you agree with this, can you please rebase & squash so we can merge? Thanks!

**Comment by grammaright** [comment]
@dimkarakostas @OrfeasLitos 
OK, I moved a line to `Scalability` and pushed a new commit.

**Pull request merged**
